//original author : Marcellas
// src/pages/management/campaign/create/index.tsx - FINAL SIMPLIFIED VERSION
import { useMutation } from "@tanstack/react-query";
import { message } from "antd";
import { useState } from "react";
import { useNavigate } from "react-router";
import campaignService from "@/api/services/campaignService";
import { Icon } from "@/components/icon";
import { Button } from "@/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/ui/card";
import { Input } from "@/ui/input";
import { Label } from "@/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/ui/select";
import { Textarea } from "@/ui/textarea";

export default function CreateCampaignPage() {
	const navigate = useNavigate();
	const [messages, setMessages] = useState([{ message: "" }]);

	const createMutation = useMutation({
		mutationFn: campaignService.createCampaign,
		onSuccess: (data) => {
			console.log("✅ Campaign created successfully:", data);
			message.success("Campaign created successfully!");
			navigate("/management/campaign/list");
		},
		onError: (error: Error) => {
			console.error("❌ Campaign creation failed:", error);

			// Enhanced error messages
			let errorMessage = error.message;
			if (error.message.includes("500")) {
				errorMessage = "Server error. Please check if all required fields are filled correctly and try again.";
			} else if (error.message.includes("400")) {
				errorMessage = "Invalid data format. Please check your input.";
			} else if (error.message.includes("Network Error")) {
				errorMessage = "Network error. Please check your connection.";
			}

			message.error(`Failed to create campaign: ${errorMessage}`);
		},
	});

	const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
		event.preventDefault();

		const formData = new FormData(event.currentTarget);

		// Get form values
		const campaignName = formData.get("name") as string;
		const campaignType = formData.get("type") as string;
		const targetAudience = formData.get("targetAudience") as string;
		const startDate = formData.get("startDate") as string;
		const endDate = formData.get("endDate") as string;
		const filteredMessages = messages.filter((msg) => msg.message.trim() !== "");

		// Validate required fields
		if (!campaignName?.trim()) {
			message.error("Campaign name is required");
			return;
		}

		if (!campaignType) {
			message.error("Campaign type is required");
			return;
		}

		if (!targetAudience?.trim()) {
			message.error("Target audience is required");
			return;
		}

		if (!startDate) {
			message.error("Start date is required");
			return;
		}

		if (!endDate) {
			message.error("End date is required");
			return;
		}

		if (filteredMessages.length === 0) {
			message.error("At least one campaign message is required");
			return;
		}

		// Validate dates
		if (new Date(startDate) >= new Date(endDate)) {
			message.error("End date must be after start date");
			return;
		}

		// SIMPLIFIED: Only send essential fields - backend handles the rest
		const campaignData = {
			campaignName: campaignName.trim(),
			campaignType: campaignType,
			targetAudience: targetAudience.trim(),
			startDate: startDate,
			endDate: endDate,
			messages: filteredMessages,
			// DO NOT include: id, createdAt, merchantId, or any complex nested objects
			// These are auto-generated by the backend
		};

		console.log("🛠️ Submitting simplified campaign data:", campaignData);

		createMutation.mutate(campaignData);
	};

	const addMessage = () => {
		setMessages([...messages, { message: "" }]);
	};

	const updateMessage = (index: number, value: string) => {
		const newMessages = [...messages];
		newMessages[index].message = value;
		setMessages(newMessages);
	};

	const removeMessage = (index: number) => {
		if (messages.length > 1) {
			setMessages(messages.filter((_, i) => i !== index));
		} else {
			// Clear the message but keep the field
			const newMessages = [...messages];
			newMessages[index].message = "";
			setMessages(newMessages);
		}
	};

	// Set minimum date to today
	const today = new Date().toISOString().split("T")[0];

	return (
		<div className="space-y-6">
			<div>
				<h1 className="text-2xl font-bold">Create New Campaign</h1>
				<p className="text-muted-foreground">Set up a new marketing campaign using the Loyalty Engine</p>
			</div>

			<Card>
				<CardHeader>
					<CardTitle>Campaign Details</CardTitle>
					<CardDescription>
						Enter the essential details for your new marketing campaign. The system will automatically generate the
						technical fields.
					</CardDescription>
				</CardHeader>
				<CardContent>
					<form onSubmit={handleSubmit} className="space-y-6">
						<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
							<div className="space-y-2">
								<Label htmlFor="name">Campaign Name *</Label>
								<Input
									id="name"
									name="name"
									placeholder="Enter campaign name"
									required
									minLength={3}
									maxLength={100}
									disabled={createMutation.isPending}
								/>
							</div>

							<div className="space-y-2">
								<Label htmlFor="type">Campaign Type *</Label>
								<Select name="type" required disabled={createMutation.isPending}>
									<SelectTrigger>
										<SelectValue placeholder="Select type" />
									</SelectTrigger>
									<SelectContent>
										<SelectItem value="EVENT">Event</SelectItem>
										<SelectItem value="PROMOTION">Promotion</SelectItem>
										<SelectItem value="SEASONAL">Seasonal</SelectItem>
										<SelectItem value="LOYALTY">Loyalty</SelectItem>
									</SelectContent>
								</Select>
							</div>

							<div className="space-y-2">
								<Label htmlFor="targetAudience">Target Audience *</Label>
								<Input
									id="targetAudience"
									name="targetAudience"
									placeholder="e.g., FOOTBALL FANS, PREMIUM USERS"
									required
									minLength={3}
									maxLength={200}
									disabled={createMutation.isPending}
								/>
							</div>

							<div className="space-y-2">
								<Label htmlFor="startDate">Start Date *</Label>
								<Input
									id="startDate"
									name="startDate"
									type="date"
									required
									min={today}
									disabled={createMutation.isPending}
									onChange={(e) => {
										// Update end date min to be after start date
										const endDateInput = document.getElementById("endDate") as HTMLInputElement;
										if (endDateInput && e.target.value) {
											endDateInput.min = e.target.value;
										}
									}}
								/>
							</div>

							<div className="space-y-2">
								<Label htmlFor="endDate">End Date *</Label>
								<Input
									id="endDate"
									name="endDate"
									type="date"
									required
									min={today}
									disabled={createMutation.isPending}
								/>
							</div>
						</div>

						{/* Campaign Messages */}
						<div className="space-y-4">
							<div className="flex items-center justify-between">
								<div>
									<Label>Campaign Messages *</Label>
									<p className="text-sm text-muted-foreground">Add messages to be sent to your target audience</p>
								</div>
								<Button
									type="button"
									variant="outline"
									size="sm"
									onClick={addMessage}
									disabled={createMutation.isPending}
								>
									<Icon icon="lucide:plus" className="mr-2" />
									Add Message
								</Button>
							</div>

							{messages.map((message, index) => (
								<div key={index} className="flex gap-2 items-start">
									<div className="flex-1">
										<Textarea
											placeholder="Enter campaign message (e.g., 'Get 20% off on all products this weekend!')"
											value={message.message}
											onChange={(e) => updateMessage(index, e.target.value)}
											rows={3}
											required={index === 0}
											minLength={10}
											maxLength={500}
											className="resize-none"
											disabled={createMutation.isPending}
										/>
										<p className="text-xs text-muted-foreground mt-1">{message.message.length}/500 characters</p>
									</div>
									{messages.length > 1 && (
										<Button
											type="button"
											variant="outline"
											size="sm"
											onClick={() => removeMessage(index)}
											className="mt-1"
											disabled={createMutation.isPending}
										>
											<Icon icon="lucide:trash-2" />
										</Button>
									)}
								</div>
							))}
						</div>

						<div className="flex gap-4 pt-4 border-t">
							<Button type="submit" disabled={createMutation.isPending} className="flex-1" size="lg">
								{createMutation.isPending ? (
									<>
										<Icon icon="eos-icons:loading" className="mr-2" />
										Creating Campaign...
									</>
								) : (
									<>
										<Icon icon="lucide:plus" className="mr-2" />
										Create Campaign
									</>
								)}
							</Button>
							<Button
								type="button"
								variant="outline"
								onClick={() => navigate("/management/campaign/list")}
								disabled={createMutation.isPending}
								size="lg"
							>
								Cancel
							</Button>
						</div>
					</form>
				</CardContent>
			</Card>
		</div>
	);
}
