// src/api/services/campaignService.ts - FINAL FIXED VERSION
import { loyaltyApiClient } from "../apiClient";

export interface CampaignMessage {
	campaignMessageId?: number;
	message: string;
	campaign?: CampaignEntity;
	messagesSent?: CampaignMessageSent[];
}

export interface CampaignMessageSent {
	campaignMessageSentId?: number;
	campaignMessage?: CampaignMessage;
	customer?: Customer;
}

export interface Customer {
	customerId?: number;
	phoneNumber: string;
	name: string;
	totalLitres: number;
	lastTransaction: string;
	createdAt: string;
	messagesReceived: CampaignMessageSent[];
	preferredMerchant: Merchant;
	customerType: "BUSINESS" | "PERSONAL";
	gender: string;
	locality: string;
	collectedBy: string;
	totalAmountSpent: number;
	totalTransactions: number;
	lastPaymentDate: string;
	averageTransactionValue: number;
	customerTier: "BRONZE" | "SILVER" | "GOLD" | "PLATINUM";
	customerSegment: string;
	lead: boolean;
}

export interface Merchant {
	id: number;
	businessName: string;
	location: string;
	tillNumber: string;
	businessType: string;
	createdAt: string;
}

export interface CampaignEntity {
	id?: number;
	campaignName: string;
	campaignType: string;
	targetAudience: string;
	startDate: string;
	endDate: string;
	createdAt?: string;
	messages: CampaignMessage[];
}

export interface ApiResponse<T = any> {
	status: string;
	message: string;
	respObject?: T;
}

// SIMPLIFIED: For creating campaigns, we only need these essential fields
export interface CreateCampaignRequest {
	campaignName: string;
	campaignType: string;
	targetAudience: string;
	startDate: string;
	endDate: string;
	messages: Array<{ message: string }>;
	// The backend will auto-generate: id, createdAt, and all complex nested objects
}

const createCampaign = (data: CreateCampaignRequest) => {
	console.log("🛠️ Creating campaign with data:", data);

	// Send only the essential fields - backend will handle auto-generation of IDs and timestamps
	const requestData = {
		campaignName: data.campaignName,
		campaignType: data.campaignType,
		targetAudience: data.targetAudience,
		startDate: data.startDate,
		endDate: data.endDate,
		messages: data.messages.map((msg) => ({
			message: msg.message,
		})),
		// DO NOT include: id, createdAt, campaignMessageId, messagesSent, merchantId, etc.
		// These are auto-generated by the backend
	};

	return loyaltyApiClient.post<ApiResponse>({
		url: "/campaigns/createCampaign",
		data: requestData,
	});
};

// FIXED: Properly accept and pass merchantId for GET requests
const getCampaigns = (merchantId: number) => {
	console.log("🛠️ Fetching campaigns for merchant:", merchantId);

	return loyaltyApiClient
		.get<any>({
			url: "/campaigns",
			params: { merchantId },
		})
		.then((response) => {
			console.log("🛠️ Campaigns API raw response:", response);

			// Handle different response formats
			if (Array.isArray(response)) {
				console.log("🛠️ Campaigns: Direct array response");
				return response;
			} else if (response?.respObject && Array.isArray(response.respObject)) {
				console.log("🛠️ Campaigns: Array in respObject");
				return response.respObject;
			} else if (response?.data && Array.isArray(response.data)) {
				console.log("🛠️ Campaigns: Array in data");
				return response.data;
			} else if (response && typeof response === "object") {
				// If it's an object but not the expected structure, try to extract any array
				const possibleArrays = Object.values(response).filter((val) => Array.isArray(val));
				if (possibleArrays.length > 0) {
					console.log("🛠️ Campaigns: Found array in object values");
					return possibleArrays[0];
				}
			}

			console.warn("🛠️ Campaigns API returned unexpected format, returning empty array:", response);
			return [];
		})
		.catch((error) => {
			console.error("🛠️ Campaigns API error:", error);
			return [];
		});
};

const getCampaignById = (id: number) =>
	loyaltyApiClient.get<CampaignEntity>({
		url: `/campaigns/${id}`,
	});

const updateCampaign = (id: number, data: CampaignEntity) =>
	loyaltyApiClient.put<CampaignEntity>({
		url: `/campaigns/${id}`,
		data,
	});

const deleteCampaign = (id: number) =>
	loyaltyApiClient.delete<void>({
		url: `/campaigns/${id}`,
	});

// Clean export
const campaignService = {
	createCampaign,
	getCampaigns,
	getCampaignById,
	updateCampaign,
	deleteCampaign,
};

export default campaignService;
